# Maintainer: Ruslan Lopushan <tguruslan1994@gmail.com>
pkgname=my-arch-meta
pkgver=0.0.1
pkgrel=1
pkgdesc="For install all required packege"
arch=('any')
url="https://github.com/tguruslan/my-arch-meta"
license=('MIT')
depends=(
  vim
  tmux
  xorg
  plasma-meta
  packagekit-qt5
  dialog
  wpa_supplicant
  wine
  vlc
  chromium
  expect
  python
  python-pip
  docker
  docker-compose
  network-manager-applet
  networkmanager
  htop
  btrfs-progs
  alsa-lib
  alsa-plugins
  gedit
  lib32-vulkan-icd-loader
  vulkan-extra-layers
  vulkan-headers
  vulkan-icd-loader
  vulkan-mesa-layer
  vulkan-tools
  vulkan-validation-layers
)
